layout: sidebar
style: light

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-remote-theme

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: devgame
    # - repo-name

social_media:

  twitter: STEMMEfatale
  linkedin: kate-harline
  instagram: yogi_saurus
  mail: harhark8@gmail.com
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  gscholar: citations?user=dR6qLhMAAAAJ&hl=en
  orcid: 0000-0002-4150-1165
  github: kateharline

  # keybase: your_username


  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username

  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
